### ISSUE TITLE
question about add-ons

### ISSUE THREAD

**Issue by hs-sean-grant** [mysticrenji/home-assistant-on-kubernetes#98]
Thank you for the amazing write up and examples. I could only read part of your writings, so apologies if this is already explained. You say in the README that the HA instance supports add-ons, does it support the official add-ons like an on-metal installation?

**Comment by mysticrenji** [comment]
Thanks for reading @hs-sean-grant . The addons mentioned in the write-up is about [Home Assistant Addons](https://www.home-assistant.io/addons/). In this case, I used the MQTT support that comes out of Home Assistant, to receive telemetrics. Sorry,  I am not sure about the on-metal case.

**Comment by mysticrenji** [comment]
![image](https://github.com/user-attachments/assets/449bb9a5-2c71-4f9e-a869-d855e53659f5)
This integration is available by default and fairly straightforward to configure. If you are self-hosting on the same hardware, you could expose it internally via the Kubernetes service.

https://www.home-assistant.io/integrations/mqtt/
